### ISSUE TITLE
The default time zone is Coordinated Universal Time (UTC), and we wish to follow the system time zone.

### ISSUE THREAD

**Issue by buzhiming999** [roovo/obsidian-card-board#187] opened 2023-12-24 18:03 UTC
The completion time is retrieved in the UTC time zone. We hope to have a setting option for modification or to follow the system time zone.  
![.](http://1.171234303.xyz:7791/i/2023/12/30/m5i7a-1.png)

**Comment by roovo** [comment] 2023-12-30 22:05
closing this as a duplicate of #115.  I am working on a batch of fixes in the next release and this is one I have included so if all goes to plan then you will be able to select to use your local time zone rather than UTC.  I take it that this would fit your use case - feel free to follow up here if not!

**Closed by roovo** 2023-12-30 22:05 UTC
Labels: kind/feature, triage/thinking
