### ISSUE TITLE
Change date of a task

### ISSUE THREAD

**Issue by TfTHacker** [roovo/obsidian-card-board#9] opened 2021-10-31 11:17 UTC
I would like the ability to change a due date without having to edit the file. Perhaps in the card, click on the date and have it give me a popup for changing the date.

Having said that, being able to drag a card to another column (or have arrows for moving right or left in the cardboard view) would be useful.

**Comment by roovo** [comment] 2021-10-31 18:38
Many thanks - I'm going to close this as a duplicate of the wider ranging #11 as this idea is captured there along with other stuff.

**Comment by roovo** [comment] 2021-11-01 09:11
I'm going to re-open this as on reflection it may be useful to think of this separately from #11 as it could be something that it would make sense to implement ahead of #11 to break things up a bit!

**Comment by darthmachina** [comment] 2021-11-01 23:46
FWIW I would like the ability to edit the date of a task directly as well. This would be useful on a Tag Board since dates aren't directly used by the board itself but it is still information on a card.

**Comment by roovo** [comment] 2024-01-28 09:10
closing as the latest release (0.7.8) adds a context menu which allows the due date of a task to be set/changed/cleared from the CardBoard view

**Closed by roovo** 2024-01-28 09:10 UTC
Labels: kind/feature, epic/drag-and-drop, triage/confirmed, lifecycle/active, lifecycle/release_ready
