### ISSUE TITLE
Duplicated tasks – caused by FS symbolic link

### ISSUE THREAD

**Issue by cernekj** [roovo/obsidian-card-board#138] opened 2023-01-31 16:25 UTC
Hi,
using of filesystem symbolic links is a good way to organize data and they work in the Obsidian Vault. But CardBoard doesn't detect them as duplicates. So the same task is shown multiple times on Tag/Date board.
Example:
```bash
Vault
└┬ _symlink-to-folder2a1
 │   ╰ file2a1a
 ├ _symlink-to-folder-outside-Vault
 │   ╰ fileY
 ├ folder1
 │   ╰ file1
 └ folder2
    └┬ folder2a
     │   └ folder2a1
     │       └ file2a1a
     └ folder2b
```

All tasks in the `file2a1a` file are duplicated in CardBoard. Tasks from the `fileY` are shown correctly and only one time each.

This plug-in doesn't detect duplicated tasks at all. General deduplication of tasks could be tricky from UX/HCI perspective, but for symlinks and hardlinks it is only technical task.

Tested on macOS 13, Obsidian 1.1.9, Obsidian CardBoard Plugin 0.7.1.

**Comment by roovo** [comment] 2023-01-31 19:06
Thanks @cernekj - I'm on a mac too so will be able to set up the same scenario to experiment.  Out of interest if you use the obsidian search function to search for something in file2a1a it is de-duped by obsidian?  (I'll obviously be able to find out later - but if you happen to know....)

[this is me pondering out loud] If it does, I am wondering how it does this - does it have a way to know that the two files are the actually the same due to symlinking - I've not delved into the Obisidian API enough to see how I would be able to detect this.... will need to have a dig around.

Thanks again - will be interesting to see how to tackle this :)

**Comment by cernekj** [comment] 2023-02-01 18:46
No, Obsidian doesn't recognize it's the same file in the search. It shows it duplicated too.

There are some bugs around symlinks and Apple Alias files in Obsidian, btw. I will report it to them, later, hopefully :-)

**Comment by roovo** [comment] 2023-02-02 08:44
Thanks for checking - really appreciated.  I will still have a look, but as I access the files via the obsidian APIs then I'm pretty sure there is no way I would be able to tell what is symlinked and what is not if Obsidian itself isn't doing this.

If there's nothing I can do I'll keep an eye out for any changes at the obsidian end which would mean I could support this...

Thank you again

**Comment by roovo** [comment] 2023-02-04 21:00
Heya - I've now had a look around in the API documentation and as far as I can tell there isn't any way to work with symbolic links in the way that you wish so I'm afraid I won't be able to do anything with this - sorry!

If obsidian changes they way that it handles symbolic links and exposes this via it's API, I could pick this up then.  So am closing this - it can be re-opened later if needed.

Many thanks

**Closed by roovo** 2023-02-04 21:00 UTC
Labels: kind/bug, triage/thinking

**Comment by cernekj** [comment] 2023-02-13 17:39
And what about Node.js `fs.Stats.isSymbolicLink()`? Like [github / chrisdmacrae / symlinks-obsidian / main.js](https://github.com/chrisdmacrae/symlinks-obsidian/blob/main/main.js#L52)

**Comment by roovo** [comment] 2023-02-15 20:34
Thanks for finding that,  however I really do need to track files via the Obsidian APIs so I can easily (like I don't have to have any code in my codebase that deals with it) track which files are being added/updated/deleted in a way that is consistent with the rest of Obsidian.  It's also not clear to be what the expected behaviour should be when symlinking files or folders within a vault, so I am intrigued as to what your use case is here (if you don't mind me asking).

**Comment by cernekj** [comment] 2023-02-16 21:56
Obsidian API can give you list of files in the Vault, or added/updated/deleted files, and plugin will evaluate if there is a symlink in the given path. If so, than follow the link and exclude duplicates.

---

The reason for my setup is productivity. I work mostly with few folders/files, but I need access to all of team files/folders too.

My Vault is like this:  (listed using modified `ls -lF`  output)
```
Inbox/
Personal TODO/
Personal KnowHow/
Project A@ -> Team1/project_A/
Project B docs@ -> Team2/repositories/project_B/docs/
Project B TODO@ -> Team2/repositories/project_B/TODO/
Team1@ -> /Volumes/samba_share_xy/
Team2@ –> /Users/user/Documents/CloudShare/team2/
```
Listing `Team2/repositories` every time is annoying (>200 folders).

In my initial report I oversimplified/generalized the example setup and made mistake BTW.
