### ISSUE TITLE
FR: Date Board: Option for Custom Columns

### ISSUE THREAD

**Issue by sstar0016** [roovo/obsidian-card-board#140] opened 2023-02-12 03:21 UTC
Thank you for this awesome plugin, love the date board, use it daily to plan my life.

Would be keen to have further options beyond just 'Future' (ie This Week, Next Week etc) so I can get a bit more of an idea of what is coming up. 

Integration with upcoming drag features (#45)  could just change the date to the start of that time period.

**Comment by roovo** [comment] 2023-02-13 19:14
Thank you and this is definitely on the radar.  Some of my recent changes have been made with this in mind and some of the next drag and drop tasks will force me to get the code in even better shape for doing this.

I am going to mark this as a duplicate of #93 so I am tracking this with just the one ticket - do sign up for notifications there if you want to track progress.  The plan will be to define columns based on whatever date ranges you wish so you should be able to get things working however you need to.

There is a big pile of drag and drop work to finish first, followed by a batch of some of the easier-to-do tickets I'd like to tackle -> then this will be a good contender - specially as I think I'll find it quite handy myself too :)

**Comment by roovo** [comment] 2023-02-13 19:15
Track at: #93

**Closed by roovo** 2023-02-13 19:15 UTC
Labels: triage/duplicate
